Servers: 1
Cpu: "0.5"
Memory: "1Gi"
Heap: "512M"
Storage: "10Gi"
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181
Image: "gcr.io/google_containers/kubernetes-zookeeper:1.0-3.4.10"
ImagePullPolicy: "Always"
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
AntiAffinity: "soft"
LogLevel: "INFO"
MaxSessionTimeout: 40000
MinSessionTimeout: 4000
UpdateStrategy: RollingUpdate
MaxUnavailable: 1